name: Test Environment Gate with pull_request_target

on:
  pull_request_target:
    types: [opened, labeled, synchronize, reopened]

permissions:
  contents: read

jobs:
  e2e-untrusted:
    runs-on: ubuntu-latest
    environment: requires-approval
    steps:
      - run: echo "Ran AFTER approval"
